export const ACTION = {
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  TODO_DATA_REQUEST: "TODO_DATA_REQUEST",
  TODO_DATA_SUCCESS: "TODO_DATA_SUCCESS",
  TODO_DATA_FAILURE: "TODO_DATA_FAILURE",

  SET_LISTENER: "SET_LISTENER",
};
