export const ACTION = {
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  CHANNELS_DATA_REQUEST: "CHANNELS_DATA_REQUEST",
  CHANNELS_DATA_SUCCESS: "CHANNELS_DATA_SUCCESS",
  CHANNELS_DATA_FAILURE: "CHANNELS_DATA_FAILURE",

  SET_LISTENER: "SET_LISTENER",
};
