export const ACTION = {
  LOGIN_EMAIL_REQUEST: "LOGIN_EMAIL_REQUEST",
  LOGIN_EMAIL_SUCCESS: "LOGIN_EMAIL_SUCCESS",
  LOGIN_EMAIL_FAILURE: "LOGIN_EMAIL_FAILURE",

  LOGIN_GOOGLE_REQUEST: "LOGIN_GOOGLE_REQUEST",
  LOGIN_GOOGLE_SUCCESS: "LOGIN_GOOGLE_SUCCESS",
  LOGIN_GOOGLE_FAILURE: "LOGIN_GOOGLE_FAILURE",

  LOGIN_FACEBOOK_REQUEST: "LOGIN_FACEBOOK_REQUEST",
  LOGIN_FACEBOOK_SUCCESS: "LOGIN_FACEBOOK_SUCCESS",
  LOGIN_FACEBOOK_FAILURE: "LOGIN_FACEBOOK_FAILURE",

  FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAILURE: "FORGOT_PASSWORD_FAILURE",

  SIGN_UP_REQUEST: "SIGN_UP_REQUEST",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};
